[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18.17.0" }

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
